#only-pre-branches: &only-pre-branches
#  filters:
#    branches:
#      only: dev
version: 2.1
jobs:
  job1:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: npm install
      - run: npm test

  job2:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: cat README.md

  cron-test:
    docker:
      -image: circleci/node:10
    steps:
      -checkout
      -run: npm test

workflows:
  version: 2

  nightly:
    triggers:
      -schedule:
        cron: "* * * * *"
    jobs:
      -cron-test

  one-and-two:
    jobs:
      - job1
#          <<: *only-pre-branches
      - job2

  two-and-three:
    jobs:
      - job1
      - job2:
          requires:
            - job1

