version: 2
jobs:
  builds:
    docker:
      - image: ubuntu:14.04

    steps:
      - run:
          name: Testing application
          command: echo 'hi'
          shell: /bin/bash
          working_directory: ~/my-app
          no_output_timeout: 30m
          environment:
            FOO: bar

      - run: echo 127.0.0.1 devhost | sudo tee -a /etc/hosts

  deploy-stage:
    docker:
      - image: ubuntu:14.04
    working_directory: /tmp/my-project
    steps:
      - save_cache:
          key: v1-myapp-cache
          paths:
            - ~/d1

      - save_cache:
          key: v1-myapp-cache-new
          paths:
            - ~/d2

      - run: rm -f ~/d1 ~/d2

      - restore_cache:
          key: v1-myapp-cache


workflows:
  version: 2
  build-deploy:
    jobs:
      - builds
      - deploy-stage:
          requires:
            - builds



