#only-pre-branches: &only-pre-branches
#  filters:
#    branches:
#      only: dev
version: 2
jobs:
  job1:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: npm install

  job2:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: cat README.md
  job3:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: npm test


workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                -dev

    one-and-two:
      jobs:
        - job1
        - job2

    two-and-three:
      jobs:
        - job1
        - job2:
            requires:
              - job1

