jobs:
  job1:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: npm install
      - run: npm test

  job2:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: cat README.md

workflows:
  version: 2
  one-and-two:
    jobs:
      - job1
      - job2

  two-and-three:
    jobs:
      - job1:
          pre-steps:
            - run:
                command: echo "install custom dependency"
          post-steps:
            - run:
                command: echo "upload artifact to s3"

