jobs:
  myjob:
    docker:
      - image: "circleci/node:9.6.1"
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - sayhello:
          to: "Lev"

  job1:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: npm install
      - run: npm test

  job2:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: cat README.md

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - main
                - dev
    jobs:
      - job1
      - job2
      - myjob

      - build:
          filters:
            branches:
              only:
                - dev

      - hold:
          type: approval
          requires:
              - job1
              - job2

      - deploy:
          type: approval
          requires:
              - hold
          filters:
            branches:
              ignore: dev

