jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    environment:
      FOO: bar
    parallelism: 1
    resource_class: large
    working_directory: ~/my-app
    steps:
      - run:
          name: Testing application
          command: make test
          shell: /bin/bash
          working_directory: ~/my-app
          no_output_timeout: 30m
          environment:
            FOO: bar

      - run: echo 127.0.0.1 devhost | sudo tee -a /etc/hosts

      - run: |
          sudo -u root createuser -h localhost --superuser ubuntu &&
          sudo createdb -h localhost test_db

      - run:
          name: Upload Failed Tests
          command: curl --data fail_tests.log http://example.com/error_logs
          when: on_fail

workflows:
 # version: 2
#  nightly:
#    triggers:
#      - schedule:
#          cron: "* * * * *"
#          filters:
#            branches:
#              only:
#                - jobs
    jobs:
      - build


#      - build:
#          filters:
#            branches:
#              only:
#                - dev
#
#      - hold:
#          type: approval
#          requires:
#              - job1
#              - job2
#
#      - deploy:
#          type: approval
#          requires:
#              - hold
#          filters:
#            branches:
#              ignore: dev

