only-pre-branches: &only-pre-branches
  filters:
    tags:
      only: v1.1
version: 2.1
jobs:
  job1:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: npm install
      - run: npm test

  job2:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: cat README.md

workflows:
  version: 2
  one-and-two:
    jobs:
      - job1:
          <<: *only-pre-branches
      - job2

  two-and-three:
    jobs:
      - job1
      - job2:
          requires:
            - job1

